# Generated by Django 5.2 on 2026-06-03 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('tipo_buque', models.CharField(max_length=50)),
                ('capacidad_carga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pais_origen', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Buque',
                'verbose_name_plural': 'Buques',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Capitan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('licencia_navegacion', models.CharField(max_length=50, unique=True)),
                ('nacionalidad', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Capitán',
                'verbose_name_plural': 'Capitanes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Muelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('capacidad_atraque', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
            ],
            options={
                'verbose_name': 'Muelle',
                'verbose_name_plural': 'Muelles',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Puerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('capacidad_maxima_buques', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
            ],
            options={
                'verbose_name': 'Puerto',
                'verbose_name_plural': 'Puertos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Atraque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='programado', max_length=20)),
                ('buque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atraques', to='puerto.buque')),
                ('capitan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atraques', to='puerto.capitan')),
                ('muelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atraques', to='puerto.muelle')),
            ],
            options={
                'verbose_name': 'Atraque',
                'verbose_name_plural': 'Atraques',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inspeccion', models.DateTimeField()),
                ('resultado', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('atraque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones', to='puerto.atraque')),
            ],
            options={
                'verbose_name': 'Inspección',
                'verbose_name_plural': 'Inspecciones',
                'ordering': ['-fecha_inspeccion'],
            },
        ),
        migrations.AddField(
            model_name='muelle',
            name='puerto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='muelles', to='puerto.puerto'),
        ),
    ]
