server {
    listen 80;
    server_name zambrano-puertos.uaeftt-ute.site 159.89.92.242;

    location = /favicon.ico { access_log off; log_not_found off; }

    location /static/ {
        alias /opt/maritimo_backend/staticfiles/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn-maritimo.sock;
    }
}
